##  After learning so much in Numpy, It's time for an assignment. 

### You are a student and today is your Numpy test. The test will consist of 10 questions, purely related to code. You need to write code for the given questions.



#### Q-1 Import Numpy and Write the code to know the version of numpy you are working on ?
Your output should look like this. <br>
NOTE : Numpy version may be different for you.

In [1]:
import numpy as np

In [2]:
## write code here
np.__version__

'1.23.5'

#### Q - Create a numpy array having elements from 1 to 16 (inclusive) and print it.
Your output should look like this.

In [3]:
import numpy as np

In [4]:
## write code here
x=np.arange(1,17)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


#### Q-3 You need to filter the previous array in such a way that , it only contains odd values.
Note : You have to use boolean indexing.<br>
Your output should look like this.

In [5]:
## write code here
x=np.arange(1,17,2)


print(x)

[ 1  3  5  7  9 11 13 15]


#### Q-4  Replace values that give remainder as 1 when divided by 2 from the above resulted array with 0
Your output should look like this.

In [6]:
## write code##
x=np.arange(1,17,1)
x[x%2==0] =0
print(x)

[ 1  0  3  0  5  0  7  0  9  0 11  0 13  0 15  0]


#### Q-5  Change the shape of above resulted array to 4x4.
Your output should look like this.

In [7]:
## write code here
i=x.reshape(4,4)

In [8]:
i

array([[ 1,  0,  3,  0],
       [ 5,  0,  7,  0],
       [ 9,  0, 11,  0],
       [13,  0, 15,  0]])

#### Q-6 Stack the resulted array with itself vertically.
Your output should look like this.

In [9]:
## write code ##


In [10]:
b=np.vstack([(i,i)])
print(b)

[[[ 1  0  3  0]
  [ 5  0  7  0]
  [ 9  0 11  0]
  [13  0 15  0]]

 [[ 1  0  3  0]
  [ 5  0  7  0]
  [ 9  0 11  0]
  [13  0 15  0]]]


#### Q-7 On this vertical stacked resulted array, reverse the column order in alternate manner. column new order = [ 2,1,4,3 ]
Your output should look like this.

In [11]:
## write code here3
b[:,[1,0,3,2]]

array([[[ 5,  0,  7,  0],
        [ 1,  0,  3,  0],
        [13,  0, 15,  0],
        [ 9,  0, 11,  0]],

       [[ 5,  0,  7,  0],
        [ 1,  0,  3,  0],
        [13,  0, 15,  0],
        [ 9,  0, 11,  0]]])

#### Q-8 Calculate , mean , median and mode of the resulting array.
Your output should look like this.

In [12]:
b

array([[[ 1,  0,  3,  0],
        [ 5,  0,  7,  0],
        [ 9,  0, 11,  0],
        [13,  0, 15,  0]],

       [[ 1,  0,  3,  0],
        [ 5,  0,  7,  0],
        [ 9,  0, 11,  0],
        [13,  0, 15,  0]]])

In [13]:
## write code here
r=np.mean(b)



In [14]:
t=np.median(b)
import statistics

#### Q-9 Create an array of 5 values , that are selected at random from the above resulted array.
Your output should look like this.

In [15]:
## write code here
np.random.randint(1,16,(2))

array([12,  9])

#### Q-10 Complete the function, that calculate the value of this function (a.k.a Binary Cross Entropy) using  Vectorization.
`Given -
    y  : a vector of N dimension,
    y^ : a vector of N dimension
    N : elements in y and y^
    Use : log base 2
    `

<img src="BCE.png" width=500>

Your output should be : 0.011179895048277702

In [17]:
def BCE(y, y_hat):
    ## write code here
    return(y*np.log(y_hat)-(1-y)*np.log(1-y_hat)).mean()

In [18]:
y = np.array([0.13,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,0.1])
y_hat = np.array([0.2,0.3,0.4,0.3,0.6,0.8,0.7,0.5,0.8,0.1])

result = BCE(y, y_hat)
print(result)

0.007749312731669802


In [19]:
BCE (y,y_hat)

0.007749312731669802